name: deploy on push
on:
  push:
    branches:
      - main
jobs:
    deploy-develop:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/develop'
        steps:
          -
            name: Checkout
            uses: actions/checkout@v3
          -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v2
          -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
          -
            name: Login to DockerHub
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKER_HUB_USERNAME }}
              password: ${{ secrets.DOCKER_HUB_TOKEN }}
          -
            name: prepare the docker-compose run
            run: |
                  ls -la /home/ubuntu/app
          -
            name: Build and push
            uses: docker/build-push-action@v4
            with:
              context: .
              push: true
              tags: kiehlz/bb-frontend:latest
    
          - 
            name: copy file via ssh password
            uses: appleboy/scp-action@v0.1.4
            with:
                host: ${{ secrets.HOST_SERVER }}
                username: ${{ secrets.SSH_USERNAME }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                port: ${{ secrets.SSH_PORT }}
                source: "docker-compose.yml"
                target: "/home/ubuntu/develop"
          - 
            name: Docker Compose
            uses: appleboy/ssh-action@master
            with:
                host: ${{ secrets.HOST_SERVER }}
                username: ${{ secrets.SSH_USERNAME }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                port: ${{ secrets.SSH_PORT }}
                script: |
                    cd /home/ubuntu/app/
                    echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin 
                    docker-compose down -rmi all
                    docker system prune -f
                    docker-compose pull
                    docker-compose up -d 
    
    