name: deploy on push
on: [push]

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: check out the code to build server
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
          run_install: false
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'pnpm'
      - name: build the code
        run: |
          pnpm install --no-frozen-lockfile
          pnpm build
      - name: copy file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.HOST_SERVER}}
          username: ${{secrets.SSH_USER_NAME}}
          port: ${{secrets.SSH_PORT}}
          key: ${{secrets.SSH_KEY}}
          source: "./*"
          target: "/var/www/html"
          strip_components: 1
