name: deploy on push
on: [push]

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: check out the code to build server
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.19.1
          cache: 'pnpm'

      - name: Set up pnpm
        uses: pnpm/action-setup@v2.2.4

      - name: Install dependencies and generate lock file
        run: |
          pnpm install
          pnpm install --frozen-lockfile

      - name: build the code
        run: |
          pnpm build

      - name: copy file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.HOST_SERVER}}
          username: ${{secrets.SSH_USER_NAME}}
          port: ${{secrets.SSH_PORT}}
          key: ${{secrets.SSH_KEY}}
          source: "./*"
          target: "/var/www/html"
          strip_components: 1